stages:
  - build
  - push
  - run_test
  - run_prod

variables:
  IMAGE_REGISTRY: nexus.valcon
  AWS_IMAGE_REGISTRY: 229135218214.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_NAME: $CI_PROJECT_NAME
  IMAGE_TAG: $CI_COMMIT_BRANCH.$CI_PIPELINE_ID
  LATEST_TAG: $CI_COMMIT_BRANCH.latest
  TAG_NAME: INVOICINGCONFSERVER_TAG

build-invoicingconfserver:
  stage: build
  script:
    - docker build -t $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $IMAGE_REGISTRY/$IMAGE_NAME:$LATEST_TAG -t $AWS_IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

push-invoicingconfserver:
  stage: push
  script:
    - docker push $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG 
    - docker push $IMAGE_REGISTRY/$IMAGE_NAME:$LATEST_TAG
    - ssh wedos "docker pull $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $AWS_IMAGE_REGISTRY
    - docker push $AWS_IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    
deploy-invoicingconfserver-test:
  stage: run_test
  only:
    - master
  script:
    - cd /home/docker/internal/test
    - export $TAG_NAME=$IMAGE_TAG
    - docker-compose up -d --no-deps $CI_PROJECT_NAME

deploy-invoicingconfserver-stage:
  stage: run_test
  only:
    - master
  script:
    - cd /home/docker/internal/stage
    - export $TAG_NAME=$IMAGE_TAG
    - docker-compose up -d --no-deps $CI_PROJECT_NAME

deploy-invoicingconfserver-prod:
  stage: run_prod
  when: manual
  only:
    - master
  script:
    - ssh wedos "cd /srv/internal && export $TAG_NAME=$IMAGE_TAG && docker-compose up -d --no-deps $CI_PROJECT_NAME"


