spring:
  profiles:
    active: test
  cloud:
    config:
      server:
        aws:
          region: eu-central-1
          bucket: app-config-service-bucket
        git:
          uri: http://git.valcon/internal/valconscconfig.git
          username: ?
          password: ?
          repos:
            production:
              pattern: '*/production'
              uri: http://git.valcon/internal/invoicingconf.git
              username: ?
              password: ?
        clone-on-start: true
  security:
    user:
      name: icuser
      password: icuser2020