apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoicing
  name: invoicing
spec:
  type: NodePort
  ports:
  - name: "invoicing-service"
    port: 8080
    nodePort: 32001
  selector:
    app: invoicing
